server:
  port: 8010

spring:
  data:
    mongodb:
      #uri: mongodb://127.0.0.1:27017/admin
      uri: mongodb://192.168.0.103:27017/admin?authSource=admin
#      port: 37017
#      password: 123456
#      host: 8.210.180.51
  # 线程池配置
  thread-pool:
    default:
      corePoolSize: 2
      maximumPoolSize: 4
      keepAliveTime: 3000
      queueCapacity: 1024
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 123456
    port: 6379
    timeout: 3000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: iqfrnlmbsllqebei
    username: 2518846094@qq.com
# JWT配置
jwt:
  # 秘钥
  secret: ji934fsfS9fA01eoPq23
  # 过期时间(毫秒)
  expiration: 36000000
  # 请求头Key
  header: JWTHeaderName

# OAuth2客户端配置
oauth2:
  clients:
    github:
      client-id: d2456e0d3f62d5838fb2
      client-name: Github
      client-name-cn: Github
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user
    qq:
      client-id: d2456e0d3f62d5838fb2
      client-name: QQ
      client-name-cn: 腾讯QQ
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user
    wechat:
      client-id: d2456e0d3f62d5838fb2
      client-name: wechat
      client-name-cn: 微信
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user
    weibo:
      client-id: d2456e0d3f62d5838fb2
      client-name: weibo
      client-name-cn: 微博
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
file:
  upload:
    path: 'E:\\db\\'

